<template>
  <div class="app-container">

  </div>
</template>

<script>
  export default {
    name: 'Change'
  }
</script>

<style lang="scss" scoped>
  .app-container{
    /* ----------------------------------------------
 * Generated by Animista on 2021-9-21 16:55:43
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */
    box-shadow: 0 2px 12px 0 rgba(0, 0, 0, 0.1);
    border-radius: 9px;
    height: 550px;
    -webkit-animation:app-container 8s linear infinite alternate both;
    animation:app-container 8s linear infinite alternate both;
    @-webkit-keyframes app-container{
      0%{background:#19dcea}
      25%{background:#b22cff}
      50%{background:#ea2222}
      75%{background:#f5be10}
      100%{background:#3bd80d}
    }
    @keyframes app-container{
      0%{background:#19dcea}
      25%{background:#b22cff}
      50%{background:#ea2222}
      75%{background:#f5be10}
      100%{background:#3bd80d}
    }
  }
</style>
